"use client";

import { useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Download, Plus, Search, Send, Ticket, Trash2 } from "lucide-react";
import { deleteSale, saveSale, saveVirtualSettings, sendVirtualAccess, setPaymentStatus } from "@/app/(app)/tickets/actions";
import { useViewer } from "@/components/shell/session-context";
import { useAction } from "@/components/shared/use-action";
import { StatusMenu } from "@/components/shared/status-menu";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ConfirmDialog, Dialog, DialogContent, SheetContent } from "@/components/ui/dialog";
import { Field, Input, Select, Textarea } from "@/components/ui/form";
import { EmptyState, FilterChip, PageHeader } from "@/components/ui/misc";
import { PAYMENT_STATUS, TICKET_CHANNELS, type PaymentStatus } from "@/lib/domain";
import { useRealtimeRefresh } from "@/lib/hooks/use-realtime-refresh";
import { formatDate, formatMoney, isoDay, toCsv } from "@/lib/utils";
import type { Targets } from "@/lib/domain";
import type { VirtualSettings } from "@/lib/settings";

type TicketType = { id: string; name: string; price: number | null; currency: string; is_virtual: boolean; is_active: boolean };
type Sale = { id: string; ticket_type_id: string; buyer_name: string; buyer_email: string | null; buyer_phone: string | null; organization: string | null;
  country: string; quantity: number; amount: number; currency: string; channel: string; payment_status: PaymentStatus; reference: string | null;
  sold_at: string; access_code: string | null; access_sent_at: string | null; notes: string | null; ticket_type: { name: string; is_virtual: boolean } | null };
type Draft = { ticket_type_id: string; buyer_name: string; buyer_email: string; buyer_phone: string; organization: string; country: string; quantity: string; amount: string;
  currency: "GHS" | "USD"; channel: "website" | "direct" | "corporate" | "sponsor" | "complimentary" | "other"; payment_status: PaymentStatus; reference: string; notes: string };
const emptyDraft = (type?: TicketType): Draft => ({ ticket_type_id: type?.id ?? "", buyer_name: "", buyer_email: "", buyer_phone: "", organization: "", country: "Ghana",
  quantity: "1", amount: type?.price == null ? "0" : String(type.price), currency: type?.currency === "USD" ? "USD" : "GHS", channel: "direct", payment_status: "paid", reference: "", notes: "" });

export function TicketsView({ ticketTypes, sales, virtual, targets }: { ticketTypes: TicketType[]; sales: Sale[]; virtual: VirtualSettings; targets: Targets }) {
  const { can } = useViewer();
  useRealtimeRefresh(["ticket_sales", "ticket_types"]);
  const router = useRouter(), pathname = usePathname(), params = useSearchParams();
  const selectedId = params.get("item"), creating = params.get("new") === "1";
  const selected = sales.find((s) => s.id === selectedId);
  const [draftState, setDraftState] = useState<{ key: string; values: Draft }>({ key: "", values: emptyDraft(ticketTypes[0]) });
  const draftKey = selectedId ?? (creating ? "new" : "");
  const draft = draftState.key === draftKey ? draftState.values : selected ? {
    ticket_type_id: selected.ticket_type_id, buyer_name: selected.buyer_name, buyer_email: selected.buyer_email ?? "", buyer_phone: selected.buyer_phone ?? "",
    organization: selected.organization ?? "", country: selected.country, quantity: String(selected.quantity), amount: String(selected.amount),
    currency: selected.currency === "USD" ? "USD" as const : "GHS" as const, channel: selected.channel as Draft["channel"], payment_status: selected.payment_status,
    reference: selected.reference ?? "", notes: selected.notes ?? "",
  } : emptyDraft(ticketTypes[0]);
  const setDraft = (values: Draft) => setDraftState({ key: draftKey, values });
  const [search, setSearch] = useState("");
  const [payment, setPayment] = useState("all");
  const [confirm, setConfirm] = useState(false);
  const [virtualDraft, setVirtualDraft] = useState({ join_url: virtual.join_url ?? "", meeting_id: virtual.meeting_id ?? "" });
  const [editingVirtual, setEditingVirtual] = useState(false);
  const [save, saving] = useAction(saveSale, { success: "Sale saved", onSuccess: ({ id }) => navigate({ new: null, item: id }) });
  const [setStatus] = useAction(setPaymentStatus, { success: "Payment updated" });
  const [remove, removing] = useAction(deleteSale, { success: "Sale removed", onSuccess: () => { setConfirm(false); navigate({ item: null }); } });
  const [sendAccess, sending] = useAction(sendVirtualAccess);
  const [saveVirtual, savingVirtual] = useAction(saveVirtualSettings, { onSuccess: () => setEditingVirtual(false) });
  function navigate(patch: Record<string, string | null>) { const next = new URLSearchParams(params.toString()); for (const [key, value] of Object.entries(patch)) { if (value) next.set(key, value); else next.delete(key); } router.replace(`${pathname}${next.size ? `?${next}` : ""}`, { scroll: false }); }
  const visible = useMemo(() => sales.filter((s) => (payment === "all" || s.payment_status === payment) && `${s.buyer_name} ${s.organization ?? ""} ${s.buyer_email ?? ""} ${s.reference ?? ""}`.toLowerCase().includes(search.toLowerCase())), [sales, payment, search]);
  const paid = sales.filter((s) => s.payment_status === "paid");
  const sold = paid.reduce((sum, s) => sum + s.quantity, 0);
  const revenue = paid.filter((s) => s.currency === "GHS").reduce((sum, s) => sum + s.amount, 0);
  function exportCsv() { const csv = toCsv([["Buyer", "Email", "Ticket", "Quantity", "Amount", "Currency", "Payment", "Channel", "Sold at"], ...visible.map((s) => [s.buyer_name, s.buyer_email, s.ticket_type?.name, s.quantity, s.amount, s.currency, PAYMENT_STATUS[s.payment_status].label, s.channel, s.sold_at])]);
    const href = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })); const a = Object.assign(document.createElement("a"), { href, download: `bgs-tickets-${isoDay()}.csv` }); a.click(); URL.revokeObjectURL(href); }

  return <>
    <PageHeader eyebrow="Commercial" title="Tickets & access" description="Record sales, follow payments and send personal virtual access codes."
      actions={<><Button variant="outline" onClick={exportCsv}><Download /> Export</Button>{can("tickets.manage") && <Button onClick={() => { setDraftState({ key: "new", values: emptyDraft(ticketTypes[0]) }); navigate({ new: "1", item: null }); }}><Plus /> Record sale</Button>}</>} />
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><Card className="p-4"><p className="text-xs text-ink-3">Paid tickets</p><p className="mt-1 text-2xl font-extrabold text-ink">{sold}{targets.tickets && <span className="ml-1 text-sm font-medium text-ink-3">/ {targets.tickets}</span>}</p></Card><Card className="p-4"><p className="text-xs text-ink-3">Recorded GHS revenue</p><p className="mt-1 text-2xl font-extrabold text-ink">{formatMoney(revenue)}</p></Card><Card className="p-4"><p className="text-xs text-ink-3">Awaiting payment</p><p className="mt-1 text-2xl font-extrabold text-ink">{sales.filter((s) => s.payment_status === "pending").length}</p></Card></div>
    <Card className="mb-4 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-ink">Virtual access</h2><p className="mt-1 text-xs text-ink-3">{virtual.join_url ? "Join link configured. Paid virtual delegates can receive their access codes." : "Add the Zoom join link before sending access details."}</p>{virtual.meeting_id && <p className="mt-1 text-xs text-ink-2">Meeting ID: {virtual.meeting_id}</p>}</div>{can("settings.manage") && <Button variant="outline" size="sm" onClick={() => setEditingVirtual(true)}>Configure</Button>}</div></Card>
    <div className="mb-3 relative"><Search className="absolute left-3 top-2.5 size-4 text-ink-3" aria-hidden /><Input aria-label="Search ticket sales" placeholder="Search buyers, organisations or references…" className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} /></div>
    <div className="scroll-none -mx-4 mb-4 flex gap-2 overflow-x-auto px-4 sm:mx-0 sm:px-0"><FilterChip active={payment === "all"} count={sales.length} onClick={() => setPayment("all")}>All</FilterChip>{(["paid", "pending", "complimentary", "refunded"] as const).map((s) => <FilterChip key={s} active={payment === s} count={sales.filter((x) => x.payment_status === s).length} onClick={() => setPayment(s)}>{PAYMENT_STATUS[s].label}</FilterChip>)}</div>
    <Card className="overflow-hidden">{visible.length === 0 ? <EmptyState icon={Ticket} title="No ticket sales match" description="Try another search or record a sale." /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-xs"><thead className="bg-surface-2 text-[11px] uppercase tracking-wider text-ink-3"><tr><th className="px-5 py-3">Buyer</th><th className="px-3 py-3">Ticket</th><th className="px-3 py-3">Quantity</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Payment</th><th className="px-5 py-3">Date</th></tr></thead><tbody className="divide-y divide-line">{visible.map((s) => <tr key={s.id} className="hover:bg-surface-2"><td className="px-5 py-3"><button onClick={() => navigate({ item: s.id, new: null })} className="font-bold text-ink hover:text-accent-ink">{s.buyer_name}</button><p className="text-ink-3">{s.organization ?? s.buyer_email}</p></td><td className="px-3 py-3 text-ink-2">{s.ticket_type?.name ?? "—"}</td><td className="px-3 py-3 text-ink-2">{s.quantity}</td><td className="px-3 py-3 font-semibold text-ink">{formatMoney(s.amount, s.currency)}</td><td className="px-3 py-3"><StatusMenu value={s.payment_status} meta={PAYMENT_STATUS} order={["paid", "pending", "complimentary", "refunded"]} label={s.buyer_name} disabled={!can("tickets.manage")} onChange={(next) => setStatus(s.id, next)} /></td><td className="px-5 py-3 text-ink-3">{formatDate(s.sold_at)}</td></tr>)}</tbody></table></div><div className="divide-y divide-line md:hidden">{visible.map((s) => <div key={s.id} className="p-4"><button className="text-left text-[13px] font-bold text-ink" onClick={() => navigate({ item: s.id, new: null })}>{s.buyer_name}</button><p className="mt-0.5 text-xs text-ink-3">{s.ticket_type?.name} · {s.quantity} × · {formatMoney(s.amount, s.currency)}</p><div className="mt-2 flex items-center justify-between"><StatusMenu value={s.payment_status} meta={PAYMENT_STATUS} order={["paid", "pending", "complimentary", "refunded"]} label={s.buyer_name} disabled={!can("tickets.manage")} onChange={(next) => setStatus(s.id, next)} /><span className="text-xs text-ink-3">{formatDate(s.sold_at)}</span></div></div>)}</div></>}</Card>
    <Dialog open={creating || !!selected} onOpenChange={(v) => { if (!v) navigate({ item: null, new: null }); }}><SheetContent title={selected ? selected.buyer_name : "Record a sale"} description={selected ? selected.ticket_type?.name : "Add a sale or allocation to the ticket ledger."} footer={can("tickets.manage") ? <><Button variant="outline" onClick={() => navigate({ item: null, new: null })}>Close</Button>{selected && <Button variant="danger-ghost" onClick={() => setConfirm(true)}><Trash2 /> Delete</Button>}<Button form="sale-form" type="submit" loading={saving}>Save sale</Button></> : undefined}>
      <form id="sale-form" className="grid gap-4" onSubmit={(e) => { e.preventDefault(); save({ ...draft, ...(selected ? { id: selected.id } : {}), quantity: Number(draft.quantity), amount: Number(draft.amount) }); }}>
        <Field label="Ticket type" htmlFor="sale-type"><Select id="sale-type" required disabled={!can("tickets.manage")} value={draft.ticket_type_id} onChange={(e) => { const type = ticketTypes.find((x) => x.id === e.target.value); setDraft({ ...draft, ticket_type_id: e.target.value, amount: type?.price == null ? draft.amount : String(type.price * Number(draft.quantity)), currency: type?.currency === "USD" ? "USD" : "GHS" }); }}><option value="">Select…</option>{ticketTypes.filter((t) => t.is_active || t.id === selected?.ticket_type_id).map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</Select></Field>
        <Field label="Buyer name" htmlFor="sale-buyer"><Input id="sale-buyer" required disabled={!can("tickets.manage")} value={draft.buyer_name} onChange={(e) => setDraft({ ...draft, buyer_name: e.target.value })} /></Field>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Email" htmlFor="sale-email" optional><Input id="sale-email" type="email" disabled={!can("tickets.manage")} value={draft.buyer_email} onChange={(e) => setDraft({ ...draft, buyer_email: e.target.value })} /></Field><Field label="Phone" htmlFor="sale-phone" optional><Input id="sale-phone" disabled={!can("tickets.manage")} value={draft.buyer_phone} onChange={(e) => setDraft({ ...draft, buyer_phone: e.target.value })} /></Field></div>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Organisation" htmlFor="sale-org" optional><Input id="sale-org" disabled={!can("tickets.manage")} value={draft.organization} onChange={(e) => setDraft({ ...draft, organization: e.target.value })} /></Field><Field label="Country" htmlFor="sale-country"><Input id="sale-country" required disabled={!can("tickets.manage")} value={draft.country} onChange={(e) => setDraft({ ...draft, country: e.target.value })} /></Field></div>
        <div className="grid gap-4 sm:grid-cols-3"><Field label="Quantity" htmlFor="sale-quantity"><Input id="sale-quantity" type="number" min="1" required disabled={!can("tickets.manage")} value={draft.quantity} onChange={(e) => setDraft({ ...draft, quantity: e.target.value })} /></Field><Field label="Amount" htmlFor="sale-amount"><Input id="sale-amount" type="number" min="0" step="0.01" required disabled={!can("tickets.manage")} value={draft.amount} onChange={(e) => setDraft({ ...draft, amount: e.target.value })} /></Field><Field label="Currency" htmlFor="sale-currency"><Select id="sale-currency" disabled={!can("tickets.manage")} value={draft.currency} onChange={(e) => setDraft({ ...draft, currency: e.target.value as Draft["currency"] })}><option value="GHS">GHS</option><option value="USD">USD</option></Select></Field></div>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Channel" htmlFor="sale-channel"><Select id="sale-channel" disabled={!can("tickets.manage")} value={draft.channel} onChange={(e) => setDraft({ ...draft, channel: e.target.value as Draft["channel"] })}>{TICKET_CHANNELS.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</Select></Field><Field label="Payment" htmlFor="sale-payment"><Select id="sale-payment" disabled={!can("tickets.manage")} value={draft.payment_status} onChange={(e) => setDraft({ ...draft, payment_status: e.target.value as PaymentStatus })}>{(["paid", "pending", "complimentary", "refunded"] as const).map((x) => <option key={x} value={x}>{PAYMENT_STATUS[x].label}</option>)}</Select></Field></div>
        <Field label="Reference" htmlFor="sale-reference" optional><Input id="sale-reference" disabled={!can("tickets.manage")} value={draft.reference} onChange={(e) => setDraft({ ...draft, reference: e.target.value })} /></Field><Field label="Notes" htmlFor="sale-notes" optional><Textarea id="sale-notes" disabled={!can("tickets.manage")} value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} /></Field>
      </form>
      {selected?.ticket_type?.is_virtual && <div className="mt-5 border-t border-line pt-4"><p className="text-xs font-bold text-ink">Virtual access</p>{selected.access_code && <p className="mt-1 font-mono text-sm font-bold text-ink">{selected.access_code}</p>}<p className="mt-1 text-xs text-ink-3">{selected.access_sent_at ? `Last sent ${formatDate(selected.access_sent_at)}` : "Not sent yet"}</p>{can("tickets.manage") && <Button className="mt-3" variant="outline" loading={sending} onClick={() => sendAccess(selected.id)}><Send /> {selected.access_sent_at ? "Resend access" : "Send access"}</Button>}</div>}
    </SheetContent></Dialog>
    <ConfirmDialog open={confirm} onOpenChange={setConfirm} title="Delete ticket sale?" description={`The sale for “${selected?.buyer_name ?? "this buyer"}” will be removed.`} destructive confirmLabel="Delete sale" loading={removing} onConfirm={() => { if (selected) remove(selected.id); }} />
    <Dialog open={editingVirtual} onOpenChange={setEditingVirtual}><DialogContent title="Virtual access settings" description="The join link is shown only after a paid delegate enters their email and personal code." footer={<><Button variant="outline" onClick={() => setEditingVirtual(false)}>Cancel</Button><Button form="virtual-form" type="submit" loading={savingVirtual}>Save settings</Button></>}><form id="virtual-form" className="grid gap-4" onSubmit={(e) => { e.preventDefault(); saveVirtual(virtualDraft); }}><Field label="Zoom join link" htmlFor="virtual-url"><Input id="virtual-url" type="url" value={virtualDraft.join_url} onChange={(e) => setVirtualDraft({ ...virtualDraft, join_url: e.target.value })} /></Field><Field label="Meeting ID" htmlFor="virtual-id" optional><Input id="virtual-id" value={virtualDraft.meeting_id} onChange={(e) => setVirtualDraft({ ...virtualDraft, meeting_id: e.target.value })} /></Field></form></DialogContent></Dialog>
  </>;
}
