"use client";

import { useState } from "react";
import Link from "next/link";
import { Bell, Mail } from "lucide-react";
import { configureScheduler, disableScheduler, saveEmailSettings, saveEventSettings, saveNotificationPrefs, saveTargets, saveWorkspaceLists, sendTestEmail } from "@/app/(app)/settings/actions";
import { useViewer } from "@/components/shell/session-context";
import { useAction } from "@/components/shared/use-action";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { Field, Input, Select, Switch, Textarea } from "@/components/ui/form";
import { PageHeader } from "@/components/ui/misc";
import { PushControls } from "@/components/settings/push-controls";
import { CATEGORIES, CATEGORY_KEYS, EMAIL_MODES, type NotificationPrefs } from "@/lib/notifications";
import type { AppSettings } from "@/lib/settings";
import { formatDateTime } from "@/lib/utils";

type Log = { id: string; to_email: string; subject: string; template: string; status: string; error: string | null; html: string | null; created_at: string };
type Job = { available: boolean; jobname: string | null; schedule: string | null; active: boolean | null; last_run: string | null; last_status: string | null; last_message: string | null };
type Tab = "event" | "targets" | "notifications" | "email" | "scheduler";
const TABS: { value: Tab; label: string; path: string; admin?: boolean }[] = [
  { value: "event", label: "Summit", path: "/settings", admin: true }, { value: "targets", label: "Targets & lists", path: "/settings?tab=targets", admin: true },
  { value: "notifications", label: "My notifications", path: "/settings/notifications" }, { value: "email", label: "Email", path: "/settings/email", admin: true },
  { value: "scheduler", label: "Scheduler", path: "/settings?tab=scheduler", admin: true },
];

export function SettingsView({ settings, prefs, logs, jobs, initialTab, defaultUrl }: { settings: AppSettings; prefs: NotificationPrefs; logs: Log[]; jobs: Job[]; initialTab: Tab; defaultUrl: string }) {
  const { can } = useViewer();
  const [tab, setTab] = useState<Tab>(initialTab);
  const [event, setEvent] = useState({ ...settings.event, starts_at: new Date(settings.event.starts_at).toISOString().slice(0, 16), whatsapp: settings.event.whatsapp ?? "", address: settings.event.address ?? "" });
  const [targets, setTargets] = useState({ tickets: String(settings.targets.tickets ?? ""), tickets_note: settings.targets.tickets_note ?? "", revenue: String(settings.targets.revenue ?? ""), sponsorship: String(settings.targets.sponsorship ?? ""), currency: settings.targets.currency });
  const [lists, setLists] = useState({ organizations: settings.organizations.join("\n"), sponsor_packages: settings.sponsor_packages.join("\n") });
  const [notificationPrefs, setNotificationPrefs] = useState(prefs);
  const [volume, setVolume] = useState(settings.email.volume);
  const [appUrl, setAppUrl] = useState(settings.scheduler.app_url ?? defaultUrl);
  const [preview, setPreview] = useState<Log | null>(null);
  const [saveEvent, savingEvent] = useAction(saveEventSettings);
  const [saveTarget, savingTargets] = useAction(saveTargets);
  const [saveLists, savingLists] = useAction(saveWorkspaceLists);
  const [savePrefs, savingPrefs] = useAction(saveNotificationPrefs);
  const [saveEmail, savingEmail] = useAction(saveEmailSettings);
  const [test, testing] = useAction(sendTestEmail);
  const [enable, enabling] = useAction(configureScheduler);
  const [disable, disabling] = useAction(disableScheduler);
  const admin = can("settings.manage");

  return <>
    <PageHeader eyebrow="Workspace" title="Settings" description="Keep the summit details, alerts and scheduled jobs accurate." />
    <div className="scroll-none -mx-4 mb-5 flex gap-1 overflow-x-auto border-b border-line px-4 sm:mx-0 sm:px-0">{TABS.filter((t) => !t.admin || admin).map((item) => <Link key={item.value} href={item.path} onClick={() => setTab(item.value)} className={`shrink-0 border-b-2 px-3 py-2.5 text-xs font-semibold ${tab === item.value ? "border-accent text-ink" : "border-transparent text-ink-3 hover:text-ink"}`}>{item.label}</Link>)}</div>
    {tab === "event" && admin && <div className="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"><Card className="p-5"><h2 className="text-sm font-bold text-ink">Summit details</h2><form className="mt-4 grid gap-4" onSubmit={(e) => { e.preventDefault(); saveEvent({ ...event, starts_at: new Date(`${event.starts_at}:00Z`).toISOString() }); }}>
      <Field label="Event name" htmlFor="event-name"><Input id="event-name" required value={event.name} onChange={(e) => setEvent({ ...event, name: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Short name" htmlFor="event-short"><Input id="event-short" required value={event.short_name} onChange={(e) => setEvent({ ...event, short_name: e.target.value })} /></Field><Field label="Date and time (Accra)" htmlFor="event-at"><Input id="event-at" type="datetime-local" required value={event.starts_at} onChange={(e) => setEvent({ ...event, starts_at: e.target.value })} /></Field></div>
      <Field label="Theme" htmlFor="event-theme"><Input id="event-theme" required value={event.theme} onChange={(e) => setEvent({ ...event, theme: e.target.value })} /></Field><Field label="Tagline" htmlFor="event-tagline"><Input id="event-tagline" required value={event.tagline} onChange={(e) => setEvent({ ...event, tagline: e.target.value })} /></Field>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Venue" htmlFor="event-venue"><Input id="event-venue" required value={event.venue} onChange={(e) => setEvent({ ...event, venue: e.target.value })} /></Field><Field label="City" htmlFor="event-city"><Input id="event-city" required value={event.city} onChange={(e) => setEvent({ ...event, city: e.target.value })} /></Field></div>
      <Field label="Convener" htmlFor="event-convener"><Input id="event-convener" required value={event.convener} onChange={(e) => setEvent({ ...event, convener: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Website" htmlFor="event-web"><Input id="event-web" type="url" required value={event.website} onChange={(e) => setEvent({ ...event, website: e.target.value })} /></Field><Field label="Email" htmlFor="event-email"><Input id="event-email" type="email" required value={event.email} onChange={(e) => setEvent({ ...event, email: e.target.value })} /></Field></div>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Phone" htmlFor="event-phone"><Input id="event-phone" required value={event.phone} onChange={(e) => setEvent({ ...event, phone: e.target.value })} /></Field><Field label="WhatsApp" htmlFor="event-whatsapp" optional><Input id="event-whatsapp" value={event.whatsapp} onChange={(e) => setEvent({ ...event, whatsapp: e.target.value })} /></Field></div><Field label="Address" htmlFor="event-address" optional><Input id="event-address" value={event.address} onChange={(e) => setEvent({ ...event, address: e.target.value })} /></Field><Button type="submit" loading={savingEvent}>Save summit details</Button>
    </form></Card><Card className="self-start p-5"><h2 className="text-sm font-bold text-ink">Where these details appear</h2><p className="mt-2 text-xs leading-relaxed text-ink-2">The event date, location and contact details appear in the overview, sidebar and branded emails. Updating them here keeps every screen aligned.</p></Card></div>}
    {tab === "targets" && admin && <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="text-sm font-bold text-ink">Commercial targets</h2><form className="mt-4 grid gap-4" onSubmit={(e) => { e.preventDefault(); saveTarget(targets); }}><Field label="Ticket target" htmlFor="target-tickets" optional><Input id="target-tickets" type="number" min="0" value={targets.tickets} onChange={(e) => setTargets({ ...targets, tickets: e.target.value })} /></Field><Field label="Ticket target note" htmlFor="target-note" optional><Input id="target-note" value={targets.tickets_note} onChange={(e) => setTargets({ ...targets, tickets_note: e.target.value })} /></Field><Field label="Revenue target" htmlFor="target-revenue" optional><Input id="target-revenue" type="number" min="0" value={targets.revenue} onChange={(e) => setTargets({ ...targets, revenue: e.target.value })} /></Field><Field label="Sponsorship target" htmlFor="target-sponsor" optional><Input id="target-sponsor" type="number" min="0" value={targets.sponsorship} onChange={(e) => setTargets({ ...targets, sponsorship: e.target.value })} /></Field><Field label="Currency" htmlFor="target-currency"><Select id="target-currency" value={targets.currency} onChange={(e) => setTargets({ ...targets, currency: e.target.value })}><option value="GHS">GHS</option><option value="USD">USD</option></Select></Field><Button type="submit" loading={savingTargets}>Save targets</Button></form></Card><Card className="p-5"><h2 className="text-sm font-bold text-ink">Workspace lists</h2><p className="mt-1 text-xs text-ink-3">One item per line. These appear in record forms.</p><form className="mt-4 grid gap-4" onSubmit={(e) => { e.preventDefault(); saveLists(lists); }}><Field label="Organisations" htmlFor="list-org"><Textarea id="list-org" rows={7} value={lists.organizations} onChange={(e) => setLists({ ...lists, organizations: e.target.value })} /></Field><Field label="Sponsor packages" htmlFor="list-packages"><Textarea id="list-packages" rows={7} value={lists.sponsor_packages} onChange={(e) => setLists({ ...lists, sponsor_packages: e.target.value })} /></Field><Button type="submit" loading={savingLists}>Save lists</Button></form></Card></div>}
    {tab === "notifications" && <Card className="max-w-3xl p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-accent-soft text-accent-ink"><Bell aria-hidden className="size-5" /></span><div><h2 className="text-sm font-bold text-ink">My notifications</h2><p className="mt-1 text-xs text-ink-3">Choose which updates reach your inbox. In-app alerts remain available.</p></div></div><div className="mt-5 divide-y divide-line">{CATEGORY_KEYS.map((key) => <div key={key} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-ink">{CATEGORIES[key].label}</p><p className="mt-0.5 text-xs text-ink-3">{CATEGORIES[key].description}</p></div><Select aria-label={`${CATEGORIES[key].label} email frequency`} className="w-40" value={notificationPrefs.email[key]} onChange={(e) => setNotificationPrefs({ ...notificationPrefs, email: { ...notificationPrefs.email, [key]: e.target.value as typeof notificationPrefs.email[typeof key] } })}>{EMAIL_MODES.map((mode) => <option key={mode.value} value={mode.value}>{mode.label}</option>)}</Select></div>)}</div><div className="mt-4 flex flex-wrap gap-6"><label className="flex items-center gap-2 text-xs font-semibold text-ink-2"><Switch checked={notificationPrefs.push} onCheckedChange={(push) => setNotificationPrefs({ ...notificationPrefs, push })} /> Web push</label><label className="flex items-center gap-2 text-xs font-semibold text-ink-2"><Switch checked={notificationPrefs.digest} onCheckedChange={(digest) => setNotificationPrefs({ ...notificationPrefs, digest })} /> Daily briefing</label></div><Button className="mt-5" loading={savingPrefs} onClick={() => savePrefs(notificationPrefs)}>Save preferences</Button><PushControls /></Card>}
    {tab === "email" && admin && <div className="grid gap-4"><Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-ink">Branded email alerts</h2><p className="mt-1 text-xs text-ink-3">Resend sends event alerts. Without a key, messages are saved as skipped for preview.</p></div><Button variant="outline" loading={testing} onClick={() => test()}><Mail /> Send test email</Button></div><div className="mt-4 flex flex-wrap items-end gap-3"><Field label="Workspace email volume" htmlFor="email-volume"><Select id="email-volume" value={volume} onChange={(e) => setVolume(e.target.value as typeof volume)}><option value="all">All events</option><option value="important">Important events only</option></Select></Field><Button loading={savingEmail} onClick={() => saveEmail(volume)}>Save</Button></div></Card><Card className="overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="text-sm font-bold text-ink">Recent email log</h2></div>{logs.length ? <div className="divide-y divide-line">{logs.map((log) => <button key={log.id} onClick={() => setPreview(log)} className="flex w-full flex-wrap items-center gap-2 px-5 py-3 text-left hover:bg-surface-2"><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-ink">{log.subject}</p><p className="mt-0.5 text-[11px] text-ink-3">{log.to_email} · {formatDateTime(log.created_at)}</p></div><Badge tone={log.status === "sent" ? "good" : log.status === "failed" ? "critical" : "warning"}>{log.status}</Badge></button>)}</div> : <p className="p-5 text-xs text-ink-3">No emails logged yet.</p>}</Card></div>}
    {tab === "scheduler" && admin && <div className="grid gap-4 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]"><Card className="p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-bold text-ink">Background scheduler</h2><Badge tone={settings.scheduler.enabled ? "good" : "neutral"}>{settings.scheduler.enabled ? "Enabled" : "Off"}</Badge></div><p className="mt-2 text-xs leading-relaxed text-ink-2">Supabase calls the publishing dispatcher every minute and sends the daily briefing at 06:00 Accra time. It also cleans old logs.</p><Field label="Public dashboard URL" htmlFor="scheduler-url" className="mt-4"><Input id="scheduler-url" type="url" value={appUrl} onChange={(e) => setAppUrl(e.target.value)} /></Field><div className="mt-4 flex gap-2"><Button loading={enabling} onClick={() => enable(appUrl)}>Enable or update</Button>{settings.scheduler.enabled && <Button variant="outline" loading={disabling} onClick={() => disable()}>Disable</Button>}</div></Card><Card className="p-5"><h2 className="text-sm font-bold text-ink">Job health</h2>{jobs.length ? <div className="mt-3 grid gap-3">{jobs.map((job, index) => <div key={job.jobname ?? index} className="border-t border-line pt-3"><p className="text-xs font-semibold text-ink">{job.jobname ?? (job.available ? "No jobs scheduled" : "pg_cron / pg_net unavailable")}</p>{job.schedule && <p className="mt-0.5 text-xs text-ink-3">{job.schedule} · {job.active ? "Active" : "Paused"}</p>}{job.last_run && <p className="mt-1 text-[11px] text-ink-3">Last run: {formatDateTime(job.last_run)} · {job.last_status}</p>}</div>)}</div> : <p className="mt-2 text-xs text-ink-3">No scheduler status available.</p>}</Card></div>}
    <Dialog open={!!preview} onOpenChange={(v) => { if (!v) setPreview(null); }}><DialogContent title={preview?.subject ?? "Email preview"} size="lg" description={preview ? `${preview.to_email} · ${preview.status}${preview.error ? ` · ${preview.error}` : ""}` : undefined}>{preview?.html ? <iframe title="Email preview" sandbox="" srcDoc={preview.html} className="h-[60dvh] w-full rounded-xl border border-line bg-white" /> : <p className="text-xs text-ink-3">No HTML preview is stored for this email.</p>}</DialogContent></Dialog>
  </>;
}
